///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoWebshop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddProduct recording.
    /// </summary>
    [TestModule("ff2f75c7-8a7b-45ae-8a98-248404c0fdc0", ModuleType.Recording, 1)]
    public partial class AddProduct : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoWebshopRepository repository.
        /// </summary>
        public static DemoWebshopRepository repo = DemoWebshopRepository.Instance;

        static AddProduct instance = new AddProduct();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddProduct()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddProduct Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SmallSearchterms' at 54;10.", repo.ApplicationUnderTest.SmallSearchtermsInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.SmallSearchterms.Click("54;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'smartphone' with focus on 'ApplicationUnderTest.SmallSearchterms'.", repo.ApplicationUnderTest.SmallSearchtermsInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.SmallSearchterms.PressKeys("smartphone");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest.SmallSearchterms'.", repo.ApplicationUnderTest.SmallSearchtermsInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SmallSearchterms.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.PictureOfSmartphone'", repo.ApplicationUnderTest.PictureOfSmartphoneInfo, new ActionTimeout(5000), new RecordItemIndex(3));
            repo.ApplicationUnderTest.PictureOfSmartphoneInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.PictureOfSmartphone'.", repo.ApplicationUnderTest.PictureOfSmartphoneInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PictureOfSmartphoneInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://demowebshop.tricentis.com/content/images/thumbs/0000190_smartphone_125.png') on item 'ApplicationUnderTest.PictureOfSmartphone'.", repo.ApplicationUnderTest.PictureOfSmartphoneInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PictureOfSmartphoneInfo, "Src", "http://demowebshop.tricentis.com/content/images/thumbs/0000190_smartphone_125.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Smartphone' at 49;9.", repo.ApplicationUnderTest.SmartphoneInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Smartphone.Click("49;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n                                Smartphone\n                            ') on item 'ApplicationUnderTest.H1TagSm'.", repo.ApplicationUnderTest.H1TagSmInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.H1TagSmInfo, "InnerText", "\n                                Smartphone\n                            ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Add to cart') on item 'ApplicationUnderTest.AddToCart.Button'.", repo.ApplicationUnderTest.AddToCart.ButtonInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AddToCart.ButtonInfo, "Value", "Add to cart");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddToCart.Button' at 33;10.", repo.ApplicationUnderTest.AddToCart.ButtonInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.AddToCart.Button.Click("33;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Home' Press with focus on 'ApplicationUnderTest.H1TagSm'.", repo.ApplicationUnderTest.H1TagSmInfo, new RecordItemIndex(10));
            Keyboard.PrepareFocus(repo.ApplicationUnderTest.H1TagSm);
            Keyboard.Press(System.Windows.Forms.Keys.Home, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SmallSearchterms' at 56;8.", repo.ApplicationUnderTest.SmallSearchtermsInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.SmallSearchterms.Click("56;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'blue' with focus on 'ApplicationUnderTest.SmallSearchterms'.", repo.ApplicationUnderTest.SmallSearchtermsInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.SmallSearchterms.PressKeys("blue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.BlueJeans1'", repo.ApplicationUnderTest.BlueJeans1Info, new ActionTimeout(5000), new RecordItemIndex(13));
            repo.ApplicationUnderTest.BlueJeans1Info.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BlueJeans1' at 40;13.", repo.ApplicationUnderTest.BlueJeans1Info, new RecordItemIndex(14));
            repo.ApplicationUnderTest.BlueJeans1.Click("40;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.PictureOfBlueJeans'", repo.ApplicationUnderTest.PictureOfBlueJeansInfo, new ActionTimeout(5000), new RecordItemIndex(15));
            repo.ApplicationUnderTest.PictureOfBlueJeansInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.PictureOfBlueJeans'.", repo.ApplicationUnderTest.PictureOfBlueJeansInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PictureOfBlueJeansInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://demowebshop.tricentis.com/content/images/thumbs/0000118_blue-jeans_300.jpeg') on item 'ApplicationUnderTest.PictureOfBlueJeans'.", repo.ApplicationUnderTest.PictureOfBlueJeansInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PictureOfBlueJeansInfo, "Src", "http://demowebshop.tricentis.com/content/images/thumbs/0000118_blue-jeans_300.jpeg");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Add to cart') on item 'ApplicationUnderTest.AddToCart.Button'.", repo.ApplicationUnderTest.AddToCart.ButtonInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AddToCart.ButtonInfo, "Value", "Add to cart");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddToCart.Button' at LowerRight.", repo.ApplicationUnderTest.AddToCart.ButtonInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.AddToCart.Button.Click(Location.LowerRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Home' Press with focus on 'ApplicationUnderTest.PictureOfBlueJeans'.", repo.ApplicationUnderTest.PictureOfBlueJeansInfo, new RecordItemIndex(20));
            Keyboard.PrepareFocus(repo.ApplicationUnderTest.PictureOfBlueJeans);
            Keyboard.Press(System.Windows.Forms.Keys.Home, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
