///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoWebshop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClearCart recording.
    /// </summary>
    [TestModule("d5bdab75-3e9d-4a59-8bfd-a3038e36709d", ModuleType.Recording, 1)]
    public partial class ClearCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoWebshopRepository repository.
        /// </summary>
        public static DemoWebshopRepository repo = DemoWebshopRepository.Instance;

        static ClearCart instance = new ClearCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClearCart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClearCart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ShoppingCart' at 26;9.", repo.ApplicationUnderTest.ShoppingCartInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.ShoppingCart.Click("26;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Removefromcart' at 7;6.", repo.ApplicationUnderTest.RemovefromcartInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Removefromcart.Click("7;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Removefromcart1' at 6;8.", repo.ApplicationUnderTest.Removefromcart1Info, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Removefromcart1.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Updatecart' at 89;16.", repo.ApplicationUnderTest.UpdatecartInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Updatecart.Click("89;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n    \n    \nYour Shopping Cart is empty!    \n') on item 'ApplicationUnderTest.DivTagYourShoppingCartIsE'.", repo.ApplicationUnderTest.DivTagYourShoppingCartIsEInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.DivTagYourShoppingCartIsEInfo, "InnerText", "\n    \n    \nYour Shopping Cart is empty!    \n");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
